### ISSUE TITLE
get mysql version error

### ISSUE THREAD

**Issue by cyberdemon8** [louisgab/devilbox-cli#1]
this line in get_current_choice function is not valid for:
mariadb-*
percona-*

`current=$(grep -Eo "^$config+[.[:digit:]]*" "$ENV_FILE" | sed "s/.*$config//g")`

**Comment by louisgab** [comment]
The script only implements the basics I needed for myself, a classic LAMP, so I did not implement all the devilbox features for now
Feel free to submit a PR if you want to add support
