### ISSUE TITLE
Feature: handle additional services with new `compose` command

### ISSUE THREAD

**Issue by llaville** [louisgab/devilbox-cli#11]
Hello,

My suggestion, is to add a new command to handle other services/containers that we could add in `docker-compose.overrride.yml` easily.

We have to fix a coding standard to make it possible.
As introduced in devilbox project itself there is a `compose/` folder with lot of `docker-compose.overrride.yml-*` files

Here are what my draft version is able to do : 

`dist/devilbox-cli.sh compose --containers` will give the current stack containers : see `DEVILBOX_CONTAINERS ` env var already available

i.e: with defaults containers
```bash
dist/devilbox-cli.sh compose --containers
[!] Stack Containers ready:
httpd
php
mysql
```

Now, if I want to launch `httpd, php, mysql` (default containers) plus `mailhog`, we have to run 

```bash
dist/devilbox-cli.sh compose --containers=mailhog
```
And the four containers will be launch

When there are many others containers, we just have to enclose list in double quote like this 

```bash
dist/devilbox-cli.sh compose --containers="mailhog portainer"
```

Hope you will like this new feature. Waiting your feedback to propose a PR.

**Comment by louisgab** [comment]
I really like the idea, seems to be really useful instead of manually changing the DEVILBOX_CONTAINERS env var then using the `restart` command

Feel free to submit your PR

BTW, I was thinking, maybe we can use the `config` command for that, something like `devilbox config --containers` and with a shorthand `devilbox c -c`, what do you think ?

**Comment by llaville** [comment]
I like your idea of persistence, but it is not yet part of my proposition.
I'll rebase my code with your master branch and then submit my PR. It will be base of chatting about this new feature.

**Comment by llaville** [comment]
I'll close this feature report, because i've made my own project to solve this : see https://github.com/llaville/devilbox-docker-compose-makefile
