### ISSUE TITLE
grep: .env: No such file or directory

### ISSUE THREAD

**Issue by ghena** [louisgab/devilbox-cli#13]
Hi,
I tried to install via npm inside devilbox ubunto instance.
I'm not able to retrive php version:
Please see the image.

![image](https://user-images.githubusercontent.com/548424/139587799-499e4ea2-4572-4c8e-9a68-e6fae21cf876.png)

Regards.
.g

**Comment by louisgab** [comment]
You misunderstood the purpose of this cli tool... It is meant for .env manipulations from your computer, not from the container
