### ISSUE TITLE
Run containers other than php, mysql, & httpd using the cli?

### ISSUE THREAD

**Issue by thomasplevy** [louisgab/devilbox-cli#3]
I'm finding this very useful but I've recently decided to add some additional services outside of the aforementioned list and I'm not finding a way to quickly start / stop these containers using this CLI.

After reviewing everything it looks like that's because these services are hardcoded into the `run` command.

I've taken a stab at rewriting the command to accommodate my requirement but I'm not super familiar with bash and ended up doing something kind of hacky to get it working to my liking.

My desire would be to be able to either specify which services I'd like to run via `run` and `stop` when calling the command, for example `devilbox run -s http mysql php mailhog`, or, alternatively, and what I've come up with, is to specify default services via a variable which will be used in favor of the currently hardcoded list if it exists. This would allow the existing default behavior to start my additional container if I decide I want an additional container. For example:

`EXPORT DEVILBOX_SERVICES="php mysql httpd mailhog`

When I run `devilbox run` it should start all of these services.

Here's the modifications I made to the compiled distribution script to make this latter option possible:

```sh
get_default_services() {
    if [ -n "$DEVILBOX_SERVICES" ]; then
        printf %s "${DEVILBOX_SERVICES}"
    else
        printf %s "httpd php mysql"
    fi
}

run_containers () {
    docker-compose up $(get_default_services)
}

run_containers_silent () {
    docker-compose up -d $(get_default_services)
}
```

If this seems like an acceptable solution I'd be happy to convert this into a useable PR and submit it for you.

Thanks,

**Comment by louisgab** [comment]
I'm ok with your solution, please submit your PR 
Thanks Thomas for your support on the project
