### ISSUE TITLE
Is it possible to install it without npm ?

### ISSUE THREAD

**Issue by panigrc** [louisgab/devilbox-cli#7]
I am not fan of installing node and npm in my local system, that's why I use Devilbox.
Could you provide instructions for manual installation ?

Thank you in advance.

**Comment by louisgab** [comment]
You can just grab the dist script with curl (or wget) like so:
`curl -O https://raw.githubusercontent.com/louisgab/devilbox-cli/master/dist/devilbox-cli.sh`
Then make it executable 
`chmod +x devilbox-cli.sh`
Finally move it to your executables folder so you can use it from terminal:
`sudo mv devilbox-cli.sh /usr/local/bin/devilbox`

the only drawback is that you will not be able to receive updates of the script, you will have to repeat the process (curl/chmod/mv) each time
