### ISSUE TITLE
devilbox run in detached mode?

### ISSUE THREAD

**Issue by Luc45** [louisgab/devilbox-cli#8]
Hi,

It seems that `devilbox run` behaves like `docker-compose up`. Is it possible to change it to make it detached? As of `docker-compose up -d`

**Comment by louisgab** [comment]
Hi Lucas, there is a `--silent` flag you can add (with` -s` shortcut) that adds the `-d` option to `docker-compose up`. 
To be clear : `devilbox r -s` <=> `docker-compose up -d`
